replicaCount: 3

container:
  image:
    repository: nginx
    tag: 1.12
  command: "java -jar /app.jar"
  port: 80
  
env:
  JAVA_OPTS: -Xmx1G


service:
  type: ClusterIP
  port: 80


resources:
  limits:
    cpu: 1000m
    memory: 1.1Gi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

